### ISSUE TITLE
Need support for Ginkgo v2

### ISSUE THREAD

**Issue by jlk** [joselitofilho/ginkgoTestExplorer#44]
Version 2 of ginkgo is now beta/RC. I don't see an issue here to track adding support for that, so thought I'd create the issue.

I already moved to the RC - GTE doesn't seem to work. After running tests with GTE, I see the following error once tests complete in terminal:

```
You're using deprecated Ginkgo functionality:
=============================================
  --reportFile is deprecated, use --junit-report instead
  Learn more at: https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#improved-reporting-infrastructure
```

That also leaves spinning wheels on the tests in the GTE sidebar. 

Happy to test support as added...

**Comment by pikojek** [comment]
I got the same issue here with the ginkgo v2

**Comment by astrieanna** [comment]
I think the fix might be as simple as changing this line: https://github.com/joselitofilho/ginkgoTestExplorer/blob/3c1ee7c51b0387534391d9f5093d4e6abb12c59f/src/ginkgoTest.ts#L104

to swap `-reportFile `  to `--junit-report=`, which should have equivalent output. (It looks like this extension uses a JUnit parser, so that should be the right report to generate.)

I'm hesitant to a submit a PR as I'm not sure how to run a modified VSCode extension locally, so I wouldn't be able to test this first.

**Comment by matdurand** [comment]
This may not be as simple as replacing the reportFile arg, since the extension should still support Gingko v1. I think we might need to detect which version of Ginkgo is installed and set the arguments accordingly. What do you think @joselitofilho ?

**Comment by joselitofilho** [comment]
This is a good idea @matdurand. Sorry for my late response @jlk and thank you. I will implement this in the next few days.

**Comment by matdurand** [comment]
@joselitofilho any update?
I tried to create a PR, but I cannot run the extension from sources. Are you using yarn or npm? and which version of nodejs ?
I'm getting "@types/xml2js/indexhas no default export" ... probably because I'm not using the same versions you are somehow. Anyway, let me know if I can help.

**Comment by joselitofilho** [comment]
Thank you @matdurand. I've been working on that. I will finish it this week.

**Comment by joselitofilho** [comment]
@matdurand just so you know, this change is a little bigger than I expected. It wasn't enough just to change from `-reportFile` to `--junit-report`.

Sorry for the delay, I'm in the process of moving to another country. I have limited time to dedicate myself to this project. But I'm getting a few hours.

**Comment by vedil** [comment]
wouldn't it be easier to move ```const ginkgoReport = "ginkgo.report";```  and make a variable where user can set it ?

**Comment by wicharek** [comment]
Hi @joselitofilho

Thanks for your extension! I have spent some time adding ginkgo v2 support and created PR. I tried to preserve v1 compatibility, but honestly didn't check v1 much. v2 works fine for me though. Hope this will be helpful.

**Comment by joselitofilho** [comment]
> Hi @joselitofilho
> 
> Thanks for your extension! I have spent some time adding ginkgo v2 support and created PR. I tried to preserve v1 compatibility, but honestly didn't check v1 much. v2 works fine for me though. Hope this will be helpful.

Thank you! I will take a look it.

**Comment by joselitofilho** [comment]
@jlk, @pikojek, @astrieanna, @matdurand, and @wicharek
Version 1.0.0 has been published with support to Ginkgo v2. 

Thank you @wicharek for your changes and all for your help.

🎉
